[[language]]
name = "latex"

[language.config.texlab]
auxDirectory = "build"

[language.config.texlab.chktex]
onOpenAndSave = true
onEdit = true

[language.config.texlab.forwardSearch]
executable = "okular"
args = ["--unique", "file:%p#src:%l%f"]

#executable = "zathura"
#args = [ "--synctex-forward", "%l:%c:%f", "%p" ]

[language.config.texlab.build]
forwardSearchAfter = true
onSave = true

executable = "latexmk"
 args = [
  "-pdf",
  "-interaction=nonstopmode",
  "-synctex=1",
  "-shell-escape",
  "-output-directory=build",
  "%f"
 ]

executable = "tectonic"
args = [
 "-X",
 "compile",
 "%f",
 "--synctex",
 "--keep-logs",
 "--keep-intermediates",
 "--outdir=build",
 "-Zshell-escape",
 ]
